export const SETTING_KEYS = {
  SITE_NAME: 'SITE_NAME',
  DOMAIN: 'DOMAIN',
  FOOTER_DISCLAIMER_HTML: 'FOOTER_DISCLAIMER_HTML',
  ALPACA_PAPER_URL: 'ALPACA_PAPER_URL',
  ALPACA_LIVE_URL: 'ALPACA_LIVE_URL',
  ALPACA_API_KEY: 'ALPACA_API_KEY',
  ALPACA_API_SECRET: 'ALPACA_API_SECRET',
  ALPACA_DATA_BASE_URL: 'ALPACA_DATA_BASE_URL',
  ALPACA_DATA_RATE_LIMIT_WAIT_SECONDS: 'ALPACA_DATA_RATE_LIMIT_WAIT_SECONDS',
  ALWAYS_VALIDATION_TICKERS: 'ALWAYS_VALIDATION_TICKERS',
  TRAINING_ALLOCATION_RATIO: 'TRAINING_ALLOCATION_RATIO',
  BACKTEST_ACTIVE_MONTHS: 'BACKTEST_ACTIVE_MONTHS',
  BACKTEST_API_SECRET: 'BACKTEST_API_SECRET',
  LOCAL_OPTIMIZATION_STEP_MULTIPLIERS: 'LOCAL_OPTIMIZATION_STEP_MULTIPLIERS',
  OPTIMIZATION_OBJECTIVE: 'OPTIMIZATION_OBJECTIVE',
  AUTO_OPTIMIZATION_ENABLED: 'AUTO_OPTIMIZATION_ENABLED',
  AUTO_OPTIMIZATION_DELAY_SECONDS: 'AUTO_OPTIMIZATION_DELAY_SECONDS',
  CANDLE_DATA_PROVIDER: 'CANDLE_DATA_PROVIDER',
  CANDLE_SYNC_MAX_CONCURRENT_UPDATES: 'CANDLE_SYNC_MAX_CONCURRENT_UPDATES',
  CANDLE_SYNC_MATCHING_RATIO_THRESHOLD: 'CANDLE_SYNC_MATCHING_RATIO_THRESHOLD',
  AUTO_DAILY_CANDLE_SYNC_ENABLED: 'AUTO_DAILY_CANDLE_SYNC_ENABLED',
  CANDLE_MISMATCH_THRESHOLD: 'CANDLE_MISMATCH_THRESHOLD',
  COMMODITY_TRUST_EXPENSE_RATIO: 'COMMODITY_TRUST_EXPENSE_RATIO',
  BOND_ETF_EXPENSE_RATIO: 'BOND_ETF_EXPENSE_RATIO',
  ETF_BASE_EXPENSE_RATIO: 'ETF_BASE_EXPENSE_RATIO',
  EODHD_API_TOKEN: 'EODHD_API_TOKEN',
  EODHD_BASE_URL: 'EODHD_BASE_URL',
  EODHD_RATE_LIMIT_WAIT_SECONDS: 'EODHD_RATE_LIMIT_WAIT_SECONDS',
  TIINGO_API_TOKEN: 'TIINGO_API_TOKEN',
  TIINGO_BASE_URL: 'TIINGO_BASE_URL',
  TIINGO_RATE_LIMIT_WAIT_SECONDS: 'TIINGO_RATE_LIMIT_WAIT_SECONDS',
  IGNORED_TICKERS: 'IGNORED_TICKERS',
  INCOME_ETF_EXPENSE_RATIO: 'INCOME_ETF_EXPENSE_RATIO',
  INVERSE_ETF_EXPENSE_RATIO: 'INVERSE_ETF_EXPENSE_RATIO',
  LEVERAGED_2X_EXPENSE_RATIO: 'LEVERAGED_2X_EXPENSE_RATIO',
  LEVERAGED_3X_EXPENSE_RATIO: 'LEVERAGED_3X_EXPENSE_RATIO',
  LEVERAGED_5X_EXPENSE_RATIO: 'LEVERAGED_5X_EXPENSE_RATIO',
  LIGHTGBM_TRAINING_START_DATE: 'LIGHTGBM_TRAINING_START_DATE',
  LIGHTGBM_TRAINING_END_DATE: 'LIGHTGBM_TRAINING_END_DATE',
  LOCAL_OPTIMIZATION_VERSION: 'LOCAL_OPTIMIZATION_VERSION',
  HETZNER_API_TOKEN: 'HETZNER_API_TOKEN',
  HETZNER_SERVER_TYPE: 'HETZNER_SERVER_TYPE',
  HETZNER_SERVER_LOCATION: 'HETZNER_SERVER_LOCATION',
  HETZNER_SSH_KEY_NAME: 'HETZNER_SSH_KEY_NAME',
  HETZNER_PRIVATE_KEY: 'HETZNER_PRIVATE_KEY',
  HETZNER_PUBLIC_KEY: 'HETZNER_PUBLIC_KEY',
  EMAIL_SECURITY_EMOJI: 'EMAIL_SECURITY_EMOJI',
  RESEND_API_KEY: 'RESEND_API_KEY',
  OPTIMIZER_TRAINING_START_DATE: 'OPTIMIZER_TRAINING_START_DATE',
  OPTIMIZER_TRAINING_END_DATE: 'OPTIMIZER_TRAINING_END_DATE',
  VERIFY_WINDOW_START_DATE: 'VERIFY_WINDOW_START_DATE',
  VERIFY_WINDOW_END_DATE: 'VERIFY_WINDOW_END_DATE',
  INVITE_LINK_VALID_DAYS: 'INVITE_LINK_VALID_DAYS',
  SESSION_COOKIE_VALID_DAYS: 'SESSION_COOKIE_VALID_DAYS',
  MTLS_ACCESS_CERT_PASSWORD: 'MTLS_ACCESS_CERT_PASSWORD',
  MAX_ALLOWED_DRAWDOWN_RATIO: 'MAX_ALLOWED_DRAWDOWN_RATIO',
  MINIMUM_DOLLAR_VOLUME_FOR_ENTRY: 'MINIMUM_DOLLAR_VOLUME_FOR_ENTRY',
  MINIMUM_DOLLAR_VOLUME_LOOKBACK: 'MINIMUM_DOLLAR_VOLUME_LOOKBACK',
  SHORT_BORROW_FEE_ANNUAL_RATE: 'SHORT_BORROW_FEE_ANNUAL_RATE',
  TRADE_CLOSE_FEE_RATE: 'TRADE_CLOSE_FEE_RATE',
  TRADE_ENTRY_PRICE_MAX: 'TRADE_ENTRY_PRICE_MAX',
  TRADE_ENTRY_PRICE_MIN: 'TRADE_ENTRY_PRICE_MIN',
  TRADE_SLIPPAGE_RATE: 'TRADE_SLIPPAGE_RATE',
  DISABLED_TEMPLATE_IDS: 'DISABLED_TEMPLATE_IDS'
} as const;

export type SettingKey = typeof SETTING_KEYS[keyof typeof SETTING_KEYS];

export const SETTING_KEY_LIST = Object.values(SETTING_KEYS) as SettingKey[];

export const SENSITIVE_SETTING_KEYS: ReadonlySet<SettingKey> = new Set([
  SETTING_KEYS.ALPACA_API_KEY,
  SETTING_KEYS.ALPACA_API_SECRET,
  SETTING_KEYS.EODHD_API_TOKEN,
  SETTING_KEYS.TIINGO_API_TOKEN,
  SETTING_KEYS.HETZNER_API_TOKEN,
  SETTING_KEYS.HETZNER_PRIVATE_KEY,
  SETTING_KEYS.HETZNER_PUBLIC_KEY,
  SETTING_KEYS.RESEND_API_KEY,
  SETTING_KEYS.MTLS_ACCESS_CERT_PASSWORD
]);

export const isSensitiveSettingKey = (key: string): key is SettingKey => (
  SENSITIVE_SETTING_KEYS.has(key as SettingKey)
);

export const DEFAULT_MTLS_ACCESS_CERT_PASSWORD = 'stratcraft';
export const DEFAULT_AUTO_OPTIMIZATION_DELAY_SECONDS = 300;

export const normalizeMtlsAccessCertPassword = (rawValue: string | null): string => {
  const trimmed = typeof rawValue === 'string' ? rawValue.trim() : '';
  if (trimmed.length > 0) {
    return trimmed;
  }
  return DEFAULT_MTLS_ACCESS_CERT_PASSWORD;
};
